### ISSUE TITLE
SyntaxError: Unexpected token . at array-differ/index.js:2

### ISSUE THREAD

**Issue by milkovsky** [phase2/drupal-lab#19]
I gen an error when I execute `bash scripts/site-setup.sh` or `npm start`. Looks like node.js syntax issue.
Could you advice what to do?

```
/path-to-project/web/themes/dashing/node_modules/gulp/node_modules/gulp-util/node_modules/array-differ/index.js:2
  module.exports = (arr, ...values) => {
                       ^
SyntaxError: Unexpected token .
```

P.S. 

```
$ nodejs --version
v0.12.15
$ npm --version
1.3.4
```

**Comment by fago** [comment]
Solution is to upgade to nodejs 4.\* - then everything works.

**Comment by milkovsky** [comment]
yep. nodejs should be upgraded.

**Comment by milkovsky** [comment]
Watch npm version as well. For me it works with npm 2.15.8.

This should be documented or added to dependencies.

**Comment by EvanLovely** [comment]
We support node versions 0.12.x, 4.x, 5.x, & 6.x using npm 2.x or 3.x - The thing you need to upgrade is npm from 1.x to at least 2.x. Adding to docs now. Happy Pattern Labbing!

**Comment by milkovsky** [comment]
New discovery. If you want to use http://p2-theme-core.readthedocs.io/en/master/icons/ npm should be at least 3. currently I am running 3.10.5.
